import type { IQuestion } from "./question.model";
import Question from "./question.model";
import Tag, { ITag } from "./tag.model";
import User, { IUser } from "./user.model";
import Answer, { IAnswer } from "./answer.model";
import Interaction, { IInteraction } from "./interaction.model";
export { Question, type IQuestion };
export { Tag, type ITag };
export { User, type IUser };
export { Answer, type IAnswer };
export { Interaction, type IInteraction };
